<?php

declare(strict_types=1);

namespace VonNeumannGame\Database;

use PDO;

final class SchemaInitializer
{
    public function __construct(
        private readonly string $driver,
    ) {}

    public function initialize(PDO $pdo): void
    {
        foreach ($this->statements() as $statement) {
            $pdo->exec($statement);
        }
    }

    /**
     * @return array<string>
     */
    private function statements(): array
    {
        $id = $this->driver === 'mysql' ? 'INT AUTO_INCREMENT PRIMARY KEY' : 'INTEGER PRIMARY KEY AUTOINCREMENT';
        $text = $this->driver === 'mysql' ? 'VARCHAR(255)' : 'TEXT';
        $nullableText = $this->driver === 'mysql' ? 'VARCHAR(255) NULL' : 'TEXT NULL';
        $nullableUrl = $this->driver === 'mysql' ? 'VARCHAR(2048) NULL' : 'TEXT NULL';
        $caseSensitiveText = $this->driver === 'mysql' ? 'VARCHAR(255) COLLATE utf8mb4_bin' : 'TEXT';
        $decimal = $this->driver === 'mysql' ? 'DOUBLE' : 'REAL';
        $boolean = $this->driver === 'mysql' ? 'BOOLEAN NOT NULL DEFAULT FALSE' : 'INTEGER NOT NULL DEFAULT 0';
        $activeMovementColumn = $this->driver === 'mysql'
            ? ",
                active_probe_id INTEGER GENERATED ALWAYS AS (CASE WHEN status IN ('preparing','accelerating','cruising','decelerating') THEN probe_id ELSE NULL END) STORED"
            : '';
        $activeAsteroidTrajectoryColumn = $this->driver === 'mysql'
            ? ",
                active_asteroid_id VARCHAR(255) GENERATED ALWAYS AS (CASE WHEN status IN ('accelerating','coasting','crossing_sector','orbiting_black_hole') THEN asteroid_id ELSE NULL END) STORED"
            : '';

        $statements = [
            "CREATE TABLE IF NOT EXISTS players (
                id $id,
                username $caseSensitiveText NOT NULL UNIQUE,
                display_name $nullableText,
                password_hash $nullableText,
                default_probe_id INTEGER NULL,
                home_sector_x INTEGER NOT NULL DEFAULT 0,
                home_sector_y INTEGER NOT NULL DEFAULT 0,
                home_sector_z INTEGER NOT NULL DEFAULT 0,
                forum_admin $boolean,
                forum_moderator $boolean,
                can_control_others $boolean,
                created_at $text NOT NULL,
                updated_at $text NOT NULL
            )",
            "CREATE INDEX IF NOT EXISTS idx_players_username ON players(username)",
            "CREATE INDEX IF NOT EXISTS idx_players_default_probe_id ON players(default_probe_id)",
            "CREATE TABLE IF NOT EXISTS player_auth_methods (
                id $id,
                player_id INTEGER NOT NULL,
                provider $text NOT NULL,
                provider_user_id $nullableText,
                password_hash $nullableText,
                created_at $text NOT NULL,
                UNIQUE(provider, provider_user_id),
                FOREIGN KEY(player_id) REFERENCES players(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_player_auth_player_id ON player_auth_methods(player_id)",
            "CREATE INDEX IF NOT EXISTS idx_player_auth_provider ON player_auth_methods(provider, provider_user_id)",
            "CREATE TABLE IF NOT EXISTS neumann_probes (
                id $id,
                player_id INTEGER NOT NULL,
                name $text NOT NULL,
                model $text NOT NULL DEFAULT 'generic',
                sector_x INTEGER NOT NULL,
                sector_y INTEGER NOT NULL,
                sector_z INTEGER NOT NULL,
                velocity_c $decimal NOT NULL DEFAULT 0,
                acceleration_c_per_day $decimal NOT NULL DEFAULT 0,
                direction_x $decimal NOT NULL DEFAULT 0,
                direction_y $decimal NOT NULL DEFAULT 0,
                direction_z $decimal NOT NULL DEFAULT 0,
                status $text NOT NULL,
                integrity_percent $decimal NOT NULL DEFAULT 100,
                energy_stored $decimal NOT NULL DEFAULT 0,
                deuterium_stock $decimal NOT NULL DEFAULT 100,
                internal_clock_rate $decimal NOT NULL DEFAULT 1,
                current_task $nullableText,
                entered_current_sector_at $text NOT NULL,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                exclude_from_stats $boolean,
                FOREIGN KEY(player_id) REFERENCES players(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_neumann_probes_player_id ON neumann_probes(player_id)",
            "CREATE INDEX IF NOT EXISTS idx_neumann_probes_sector ON neumann_probes(sector_x, sector_y, sector_z)",
            "CREATE TABLE IF NOT EXISTS mannies (
                id $id,
                uid $text NOT NULL UNIQUE,
                probe_id INTEGER NULL,
                storage_container_id INTEGER NULL,
                name $text NOT NULL,
                location_type $text NOT NULL,
                sector_x INTEGER NULL,
                sector_y INTEGER NULL,
                sector_z INTEGER NULL,
                current_task $nullableText,
                task_started_at $nullableText,
                task_ends_at $nullableText,
                task_scheduled_event_id INTEGER NULL,
                reserved_cargo_type $nullableText,
                reserved_cargo_space $decimal NOT NULL DEFAULT 0,
                reserved_storage_container_id INTEGER NULL,
                cargo_deuterium $decimal NOT NULL DEFAULT 0,
                cargo_metals $decimal NOT NULL DEFAULT 0,
                cargo_ice $decimal NOT NULL DEFAULT 0,
                cargo_organic_compounds $decimal NOT NULL DEFAULT 0,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                UNIQUE(probe_id, name),
                FOREIGN KEY(probe_id) REFERENCES neumann_probes(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_mannies_probe_id ON mannies(probe_id)",
            "CREATE INDEX IF NOT EXISTS idx_mannies_uid ON mannies(uid)",
            "CREATE INDEX IF NOT EXISTS idx_mannies_sector ON mannies(sector_x, sector_y, sector_z)",
            "CREATE INDEX IF NOT EXISTS idx_mannies_storage_container_id ON mannies(storage_container_id)",
            "CREATE INDEX IF NOT EXISTS idx_mannies_task_scheduled_event_id ON mannies(task_scheduled_event_id)",
            "CREATE TABLE IF NOT EXISTS probe_items (
                id $id,
                uid $text NOT NULL UNIQUE,
                probe_id INTEGER NOT NULL,
                storage_container_id INTEGER NULL,
                type $text NOT NULL,
                name $text NOT NULL,
                container_space $decimal NOT NULL,
                recipe $nullableText,
                crafting_run_id $nullableText,
                crafted_by_manny_id $nullableText,
                crafted_by_manny_name $nullableText,
                crafted_at $nullableText,
                fabricator $nullableText,
                capacity_bonus $decimal NOT NULL DEFAULT 0,
                restored_detached_container_source_uid $nullableText,
                audit_metadata_json TEXT NOT NULL,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                FOREIGN KEY(probe_id) REFERENCES neumann_probes(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_probe_items_probe_id ON probe_items(probe_id)",
            "CREATE INDEX IF NOT EXISTS idx_probe_items_uid ON probe_items(uid)",
            "CREATE INDEX IF NOT EXISTS idx_probe_items_restored_source ON probe_items(probe_id, restored_detached_container_source_uid)",
            "CREATE INDEX IF NOT EXISTS idx_probe_items_storage_container_id ON probe_items(storage_container_id)",
            "CREATE TABLE IF NOT EXISTS probe_improvement_blueprints (
                id $id,
                player_id INTEGER NOT NULL,
                improvement $text NOT NULL,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                UNIQUE(player_id, improvement),
                FOREIGN KEY(player_id) REFERENCES players(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_probe_improvement_blueprints_player_id ON probe_improvement_blueprints(player_id)",
            "CREATE TABLE IF NOT EXISTS probe_improvement_installations (
                id $id,
                probe_id INTEGER NOT NULL,
                improvement $text NOT NULL,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                UNIQUE(probe_id, improvement),
                FOREIGN KEY(probe_id) REFERENCES neumann_probes(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_probe_improvement_installations_probe_id ON probe_improvement_installations(probe_id)",
            "CREATE TABLE IF NOT EXISTS storage_containers (
                id $id,
                uid $text NOT NULL,
                probe_id INTEGER NOT NULL,
                kind $text NOT NULL,
                label $text NOT NULL,
                sort_order INTEGER NOT NULL,
                capacity $decimal NOT NULL DEFAULT 1,
                priority_filter_json TEXT NOT NULL,
                exclusion_filter_json TEXT NOT NULL,
                strict_exclusion_filter_json TEXT NOT NULL,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                UNIQUE(probe_id, uid),
                FOREIGN KEY(probe_id) REFERENCES neumann_probes(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_storage_containers_probe_id ON storage_containers(probe_id)",
            "CREATE TABLE IF NOT EXISTS storage_container_resources (
                id $id,
                container_id INTEGER NOT NULL,
                resource_type $text NOT NULL,
                amount $decimal NOT NULL DEFAULT 0,
                updated_at $text NOT NULL,
                UNIQUE(container_id, resource_type),
                FOREIGN KEY(container_id) REFERENCES storage_containers(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_storage_container_resources_container_id ON storage_container_resources(container_id)",
            "CREATE TABLE IF NOT EXISTS detached_storage_containers (
                object_id $text PRIMARY KEY,
                source_container_uid $text NOT NULL,
                sector_x INTEGER NOT NULL,
                sector_y INTEGER NOT NULL,
                sector_z INTEGER NOT NULL,
                mode $text NOT NULL,
                status $text NOT NULL DEFAULT 'available',
                reserved_by_manny_id INTEGER NULL,
                owner_probe_id INTEGER NOT NULL,
                owner_player_id INTEGER NOT NULL,
                origin_probe_id INTEGER NULL,
                target_object_id $nullableText,
                name $nullableText,
                description TEXT NULL,
                container_kind $text NOT NULL,
                container_label $text NOT NULL,
                container_sort_order INTEGER NOT NULL,
                capacity $decimal NOT NULL,
                capacity_unit $text NOT NULL,
                created_at $text NOT NULL,
                updated_at $text NOT NULL
            )",
            "CREATE INDEX IF NOT EXISTS idx_detached_storage_containers_sector ON detached_storage_containers(sector_x, sector_y, sector_z)",
            "CREATE INDEX IF NOT EXISTS idx_detached_storage_containers_status ON detached_storage_containers(status, reserved_by_manny_id)",
            "CREATE INDEX IF NOT EXISTS idx_detached_storage_containers_source_uid ON detached_storage_containers(source_container_uid)",
            "CREATE INDEX IF NOT EXISTS idx_detached_storage_containers_target ON detached_storage_containers(sector_x, sector_y, sector_z, target_object_id)",
            "CREATE TABLE IF NOT EXISTS detached_storage_container_resources (
                container_object_id $text NOT NULL,
                resource_type $text NOT NULL,
                amount $decimal NOT NULL,
                PRIMARY KEY(container_object_id, resource_type),
                FOREIGN KEY(container_object_id) REFERENCES detached_storage_containers(object_id) ON DELETE CASCADE
            )",
            "CREATE TABLE IF NOT EXISTS detached_storage_container_items (
                id $id,
                container_object_id $text NOT NULL,
                uid $text NOT NULL,
                type $text NOT NULL,
                name $text NOT NULL,
                container_space $decimal NOT NULL,
                recipe $nullableText,
                crafting_run_id $nullableText,
                crafted_by_manny_id $nullableText,
                crafted_by_manny_name $nullableText,
                crafted_at $nullableText,
                fabricator $nullableText,
                capacity_bonus $decimal NOT NULL DEFAULT 0,
                restored_detached_container_source_uid $nullableText,
                audit_metadata_json TEXT NOT NULL,
                is_backing_item $boolean,
                UNIQUE(container_object_id, uid),
                FOREIGN KEY(container_object_id) REFERENCES detached_storage_containers(object_id) ON DELETE CASCADE
            )",
            "CREATE INDEX IF NOT EXISTS idx_detached_storage_container_items_container ON detached_storage_container_items(container_object_id)",
            "CREATE TABLE IF NOT EXISTS detached_storage_container_rules (
                container_object_id $text NOT NULL,
                rule_kind $text NOT NULL,
                resource_type $text NOT NULL,
                sort_order INTEGER NOT NULL,
                PRIMARY KEY(container_object_id, rule_kind, resource_type),
                FOREIGN KEY(container_object_id) REFERENCES detached_storage_containers(object_id) ON DELETE CASCADE
            )",
            "CREATE TABLE IF NOT EXISTS detached_storage_container_discoveries (
                container_object_id $text NOT NULL,
                player_id INTEGER NOT NULL,
                discovered_at $text NOT NULL,
                PRIMARY KEY(container_object_id, player_id),
                FOREIGN KEY(container_object_id) REFERENCES detached_storage_containers(object_id) ON DELETE CASCADE
            )",
            "CREATE TABLE IF NOT EXISTS detached_storage_container_bookmarks (
                container_object_id $text NOT NULL,
                player_id INTEGER NOT NULL,
                name $text NOT NULL,
                player_name $text NOT NULL,
                created_at $text NOT NULL,
                PRIMARY KEY(container_object_id, player_id, name),
                FOREIGN KEY(container_object_id) REFERENCES detached_storage_containers(object_id) ON DELETE CASCADE
            )",
            "CREATE TABLE IF NOT EXISTS probe_movements (
                id $id,
                probe_id INTEGER NOT NULL,
                origin_x INTEGER NOT NULL,
                origin_y INTEGER NOT NULL,
                origin_z INTEGER NOT NULL,
                target_x INTEGER NOT NULL,
                target_y INTEGER NOT NULL,
                target_z INTEGER NOT NULL,
                distance INTEGER NOT NULL,
                status $text NOT NULL,
                started_at $text NOT NULL,
                preparation_ends_at $text NOT NULL,
                acceleration_ends_at $text NOT NULL,
                cruise_ends_at $text NOT NULL,
                deceleration_ends_at $text NOT NULL,
                arrival_at $text NOT NULL,
                fuel_cost_deuterium $decimal NOT NULL,
                destruction_checked_at $nullableText,
                destroyed_at $nullableText,
                destruction_reason $nullableText,
                created_at $text NOT NULL,
                updated_at $text NOT NULL$activeMovementColumn,
                FOREIGN KEY(probe_id) REFERENCES neumann_probes(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_probe_movements_probe_status ON probe_movements(probe_id, status)",
            $this->driver === 'sqlite'
                ? "CREATE UNIQUE INDEX IF NOT EXISTS idx_probe_movements_one_active_per_probe ON probe_movements(probe_id) WHERE status IN ('preparing','accelerating','cruising','decelerating')"
                : "CREATE UNIQUE INDEX IF NOT EXISTS idx_probe_movements_one_active_per_probe ON probe_movements(active_probe_id)",
            "CREATE TABLE IF NOT EXISTS probe_messages (
                id $id,
                sender_type $text NOT NULL DEFAULT 'probe',
                sender_id $text NOT NULL,
                sender_name $nullableText,
                sender_probe_id INTEGER NULL,
                recipient_type $text NOT NULL DEFAULT 'probe',
                recipient_id $text NOT NULL,
                recipient_name $nullableText,
                recipient_probe_id INTEGER NULL,
                sector_x INTEGER NOT NULL,
                sector_y INTEGER NOT NULL,
                sector_z INTEGER NOT NULL,
                body TEXT NOT NULL,
                status $text NOT NULL,
                read_at $nullableText,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                FOREIGN KEY(sender_probe_id) REFERENCES neumann_probes(id),
                FOREIGN KEY(recipient_probe_id) REFERENCES neumann_probes(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_probe_messages_recipient ON probe_messages(recipient_probe_id, status, created_at)",
            "CREATE INDEX IF NOT EXISTS idx_probe_messages_sender ON probe_messages(sender_probe_id, created_at)",
            $this->driver === 'mysql'
                ? "CREATE INDEX IF NOT EXISTS idx_probe_messages_recipient_endpoint ON probe_messages(recipient_type(32), recipient_id(191), status(32), created_at(32))"
                : "CREATE INDEX IF NOT EXISTS idx_probe_messages_recipient_endpoint ON probe_messages(recipient_type, recipient_id, status, created_at)",
            $this->driver === 'mysql'
                ? "CREATE INDEX IF NOT EXISTS idx_probe_messages_sender_endpoint ON probe_messages(sender_type(32), sender_id(191), created_at(32))"
                : "CREATE INDEX IF NOT EXISTS idx_probe_messages_sender_endpoint ON probe_messages(sender_type, sender_id, created_at)",
            "CREATE TABLE IF NOT EXISTS probe_logbook_pages (
                id $id,
                probe_id INTEGER NOT NULL,
                title $text NOT NULL,
                content TEXT NOT NULL,
                sort_order INTEGER NOT NULL,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                FOREIGN KEY(probe_id) REFERENCES neumann_probes(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_probe_logbook_pages_probe_order ON probe_logbook_pages(probe_id, sort_order, id)",
            "CREATE TABLE IF NOT EXISTS probe_missions (
                id $id,
                uid $text NOT NULL UNIQUE,
                player_id INTEGER NOT NULL,
                type $text NOT NULL,
                title $text NOT NULL,
                description TEXT NULL,
                status $text NOT NULL,
                step_order $text NOT NULL,
                metadata_json TEXT NOT NULL,
                created_by_event_json TEXT NULL,
                started_at $text NOT NULL,
                completed_at $nullableText,
                failed_at $nullableText,
                abandoned_at $nullableText,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                FOREIGN KEY(player_id) REFERENCES players(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_probe_missions_player_status ON probe_missions(player_id, status, created_at)",
            "CREATE INDEX IF NOT EXISTS idx_probe_missions_uid ON probe_missions(uid)",
            "CREATE TABLE IF NOT EXISTS probe_mission_steps (
                id $id,
                uid $text NOT NULL UNIQUE,
                mission_id INTEGER NOT NULL,
                sort_order INTEGER NOT NULL,
                title $text NOT NULL,
                description TEXT NULL,
                status $text NOT NULL,
                metadata_json TEXT NOT NULL,
                completed_at $nullableText,
                failed_at $nullableText,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                FOREIGN KEY(mission_id) REFERENCES probe_missions(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_probe_mission_steps_mission_order ON probe_mission_steps(mission_id, sort_order, id)",
            "CREATE INDEX IF NOT EXISTS idx_probe_mission_steps_uid ON probe_mission_steps(uid)",
            "CREATE TABLE IF NOT EXISTS probe_damage_warnings (
                id $id,
                probe_id INTEGER NOT NULL,
                movement_id INTEGER NULL,
                type $text NOT NULL,
                status $text NOT NULL,
                phase $text NOT NULL,
                scheduled_at $text NOT NULL,
                sector_x INTEGER NOT NULL,
                sector_y INTEGER NOT NULL,
                sector_z INTEGER NOT NULL,
                container_id $text NOT NULL,
                container_label $text NOT NULL,
                object_id $text NOT NULL,
                risk_percent $decimal NOT NULL,
                additional_container_count INTEGER NOT NULL,
                message TEXT NOT NULL,
                illustration_image_url $nullableUrl,
                read_at $nullableText,
                resolved_at $nullableText,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                FOREIGN KEY(probe_id) REFERENCES neumann_probes(id),
                FOREIGN KEY(movement_id) REFERENCES probe_movements(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_probe_damage_warnings_probe_status ON probe_damage_warnings(probe_id, status, created_at)",
            "CREATE INDEX IF NOT EXISTS idx_probe_damage_warnings_movement ON probe_damage_warnings(movement_id)",
            "CREATE TABLE IF NOT EXISTS asteroid_trajectories (
                id $id,
                uid $text NOT NULL UNIQUE,
                asteroid_id $text NOT NULL,
                mode $text NOT NULL,
                status $text NOT NULL,
                origin_sector_x INTEGER NOT NULL,
                origin_sector_y INTEGER NOT NULL,
                origin_sector_z INTEGER NOT NULL,
                current_sector_x INTEGER NOT NULL,
                current_sector_y INTEGER NOT NULL,
                current_sector_z INTEGER NOT NULL,
                direction_x INTEGER NULL,
                direction_y INTEGER NULL,
                direction_z INTEGER NULL,
                target_object_id $nullableText,
                target_probe_id INTEGER NULL,
                target_speed_c $decimal NULL,
                asteroid_mass_earth $decimal NOT NULL,
                star_mass_solar $decimal NULL,
                acceleration_started_at $nullableText,
                acceleration_ends_at $nullableText,
                revolution_duration_seconds INTEGER NULL,
                planned_revolutions INTEGER NULL,
                next_transition_at $text NOT NULL,
                sectors_crossed INTEGER NOT NULL DEFAULT 0,
                capture_penalty_steps INTEGER NOT NULL DEFAULT 0,
                missile_hits INTEGER NOT NULL DEFAULT 0,
                maximum_sector_crossings INTEGER NOT NULL,
                result $nullableText,
                failure_reason $nullableText,
                asteroid_snapshot_json TEXT NOT NULL,
                attachments_snapshot_json TEXT NOT NULL,
                created_at $text NOT NULL,
                updated_at $text NOT NULL
                $activeAsteroidTrajectoryColumn
            )",
            "CREATE INDEX IF NOT EXISTS idx_asteroid_trajectories_status_due ON asteroid_trajectories(status, next_transition_at)",
            "CREATE INDEX IF NOT EXISTS idx_asteroid_trajectories_sector ON asteroid_trajectories(current_sector_x, current_sector_y, current_sector_z)",
            $this->driver === 'sqlite'
                ? "CREATE UNIQUE INDEX IF NOT EXISTS idx_asteroid_trajectories_one_active_per_asteroid
                   ON asteroid_trajectories(asteroid_id)
                   WHERE status IN ('accelerating','coasting','crossing_sector','orbiting_black_hole')"
                : "CREATE UNIQUE INDEX IF NOT EXISTS idx_asteroid_trajectories_one_active_per_asteroid ON asteroid_trajectories(active_asteroid_id)",
            "CREATE TABLE IF NOT EXISTS scheduled_events (
                id $id,
                type $text NOT NULL,
                entity_type $text NOT NULL,
                entity_id INTEGER NOT NULL,
                run_at $text NOT NULL,
                status $text NOT NULL,
                payload_json TEXT NOT NULL,
                attempts INTEGER NOT NULL DEFAULT 0,
                locked_at $nullableText,
                locked_by $nullableText,
                processed_at $nullableText,
                last_error TEXT NULL,
                created_at $text NOT NULL,
                updated_at $text NOT NULL
            )",
            "CREATE INDEX IF NOT EXISTS idx_scheduled_events_due ON scheduled_events(status, run_at)",
            "CREATE INDEX IF NOT EXISTS idx_scheduled_events_entity ON scheduled_events(entity_type, entity_id)",
            "CREATE TABLE IF NOT EXISTS manny_tasks (
                id $id,
                manny_id INTEGER NOT NULL UNIQUE,
                scheduled_event_id INTEGER NOT NULL UNIQUE,
                task_type $text NOT NULL,
                recipe $nullableText,
                crafting_run_id $nullableText,
                resource_type $nullableText,
                target_amount $decimal NULL,
                extracted_amount $decimal NULL,
                object_id $nullableText,
                target_object_id $nullableText,
                target_container_id $nullableText,
                source_container_id $nullableText,
                destination_container_id $nullableText,
                target_probe_id INTEGER NULL,
                relay_id INTEGER NULL,
                improvement $nullableText,
                result $nullableText,
                failure_reason $nullableText,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                FOREIGN KEY(manny_id) REFERENCES mannies(id) ON DELETE CASCADE,
                FOREIGN KEY(scheduled_event_id) REFERENCES scheduled_events(id) ON DELETE CASCADE
            )",
            "CREATE INDEX IF NOT EXISTS idx_manny_tasks_type ON manny_tasks(task_type)",
            "CREATE INDEX IF NOT EXISTS idx_manny_tasks_object ON manny_tasks(object_id)",
            "CREATE TABLE IF NOT EXISTS manny_task_consumed_items (
                id $id,
                manny_task_id INTEGER NOT NULL,
                sort_order INTEGER NOT NULL,
                uid $text NOT NULL,
                type $text NOT NULL,
                name $text NOT NULL,
                container_space $decimal NOT NULL,
                storage_container_id INTEGER NULL,
                metadata_json TEXT NOT NULL,
                UNIQUE(manny_task_id, sort_order),
                FOREIGN KEY(manny_task_id) REFERENCES manny_tasks(id) ON DELETE CASCADE
            )",
            "CREATE INDEX IF NOT EXISTS idx_manny_task_consumed_items_task ON manny_task_consumed_items(manny_task_id)",
            "CREATE TABLE IF NOT EXISTS scut_networks (
                id $id,
                name $text NOT NULL,
                created_at $text NOT NULL,
                updated_at $text NOT NULL
            )",
            "CREATE TABLE IF NOT EXISTS scut_relays (
                id $id,
                created_by_probe_id INTEGER NULL,
                sector_x INTEGER NOT NULL,
                sector_y INTEGER NOT NULL,
                sector_z INTEGER NOT NULL,
                status $text NOT NULL,
                network_id INTEGER NULL,
                is_transit_beacon INTEGER NOT NULL DEFAULT 0,
                created_at $text NOT NULL,
                activated_at $nullableText,
                updated_at $text NOT NULL,
                FOREIGN KEY(network_id) REFERENCES scut_networks(id)
            )",
            "CREATE TABLE IF NOT EXISTS scut_covered_sectors (
                id $id,
                scut_network_id INTEGER NULL,
                scut_relay_id INTEGER NOT NULL,
                sector_x INTEGER NOT NULL,
                sector_y INTEGER NOT NULL,
                sector_z INTEGER NOT NULL,
                FOREIGN KEY(scut_network_id) REFERENCES scut_networks(id) ON DELETE CASCADE,
                FOREIGN KEY(scut_relay_id) REFERENCES scut_relays(id) ON DELETE CASCADE
            )",
            "CREATE INDEX IF NOT EXISTS idx_scut_relays_sector ON scut_relays(sector_x, sector_y, sector_z)",
            "CREATE INDEX IF NOT EXISTS idx_scut_relays_status_sector ON scut_relays(status, sector_x, sector_y, sector_z)",
            "CREATE INDEX IF NOT EXISTS idx_scut_relays_network ON scut_relays(network_id)",
            "CREATE UNIQUE INDEX IF NOT EXISTS idx_scut_covered_sectors_relay_sector ON scut_covered_sectors(scut_relay_id, sector_x, sector_y, sector_z)",
            "CREATE INDEX IF NOT EXISTS idx_scut_covered_sectors_network_sector ON scut_covered_sectors(scut_network_id, sector_x, sector_y, sector_z)",
            "CREATE INDEX IF NOT EXISTS idx_scut_covered_sectors_sector ON scut_covered_sectors(sector_x, sector_y, sector_z)",
            "CREATE TABLE IF NOT EXISTS visited_sectors (
                id $id,
                player_id INTEGER NOT NULL,
                probe_id INTEGER NOT NULL,
                sector_x INTEGER NOT NULL,
                sector_y INTEGER NOT NULL,
                sector_z INTEGER NOT NULL,
                first_visited_at $text NOT NULL,
                last_visited_at $text NOT NULL,
                visit_count INTEGER NOT NULL DEFAULT 1,
                UNIQUE(probe_id, sector_x, sector_y, sector_z),
                FOREIGN KEY(player_id) REFERENCES players(id),
                FOREIGN KEY(probe_id) REFERENCES neumann_probes(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_visited_sectors_player_id ON visited_sectors(player_id)",
            "CREATE INDEX IF NOT EXISTS idx_visited_sectors_player_coords ON visited_sectors(player_id, sector_x, sector_y, sector_z)",
            "CREATE INDEX IF NOT EXISTS idx_visited_sectors_probe_id ON visited_sectors(probe_id)",
            "CREATE TABLE IF NOT EXISTS sessions (
                id $id,
                player_id INTEGER NOT NULL,
                token_hash $text NOT NULL UNIQUE,
                created_at $text NOT NULL,
                expires_at $text NOT NULL,
                last_used_at $text NOT NULL,
                remember_me $boolean,
                revoked_at $nullableText,
                FOREIGN KEY(player_id) REFERENCES players(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_sessions_player_id ON sessions(player_id)",
            "CREATE INDEX IF NOT EXISTS idx_sessions_token_hash ON sessions(token_hash)",
            "CREATE TABLE IF NOT EXISTS api_keys (
                id $id,
                player_id INTEGER NOT NULL,
                token_hash $text NOT NULL UNIQUE,
                label $text NOT NULL,
                last_four $text NOT NULL,
                created_at $text NOT NULL,
                last_used_at $nullableText,
                revoked_at $nullableText,
                FOREIGN KEY(player_id) REFERENCES players(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_api_keys_player_id ON api_keys(player_id)",
            "CREATE INDEX IF NOT EXISTS idx_api_keys_token_hash ON api_keys(token_hash)",
            "CREATE TABLE IF NOT EXISTS others_idempotency_keys (
                id $id,
                player_id INTEGER NOT NULL,
                idempotency_key $caseSensitiveText NOT NULL,
                request_method $text NOT NULL,
                request_path $text NOT NULL,
                request_body_hash $text NOT NULL,
                response_status INTEGER NOT NULL,
                response_body_json TEXT NOT NULL,
                action_public_id $nullableText,
                created_at $text NOT NULL,
                UNIQUE(player_id, idempotency_key),
                FOREIGN KEY(player_id) REFERENCES players(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_others_idempotency_player ON others_idempotency_keys(player_id)",
            "CREATE TABLE IF NOT EXISTS others_operator_audit (
                id $id,
                player_id INTEGER NULL,
                source $text NOT NULL,
                command $text NOT NULL,
                entity_public_id $nullableText,
                outcome $text NOT NULL,
                details_json TEXT NOT NULL,
                created_at $text NOT NULL,
                FOREIGN KEY(player_id) REFERENCES players(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_others_operator_audit_player_created ON others_operator_audit(player_id, created_at)",
            "CREATE TABLE IF NOT EXISTS others_fleets (
                id $id,
                public_id $caseSensitiveText NOT NULL UNIQUE,
                player_id INTEGER NOT NULL,
                status $text NOT NULL DEFAULT 'active',
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                dissolved_at $nullableText,
                FOREIGN KEY(player_id) REFERENCES players(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_others_fleets_player_status ON others_fleets(player_id, status, public_id)",
            "CREATE TABLE IF NOT EXISTS others_ships (
                id $id,
                public_id $caseSensitiveText NOT NULL UNIQUE,
                fleet_id INTEGER NOT NULL,
                type $text NOT NULL,
                status $text NOT NULL DEFAULT 'inactive',
                sector_x INTEGER NOT NULL,
                sector_y INTEGER NOT NULL,
                sector_z INTEGER NOT NULL,
                integrity INTEGER NOT NULL,
                max_integrity INTEGER NOT NULL,
                deuterium_stock $decimal NOT NULL DEFAULT 0,
                deuterium_capacity $decimal NOT NULL,
                deuterium_reserved $decimal NOT NULL DEFAULT 0,
                inventory_capacity $decimal NOT NULL,
                inventory_reserved $decimal NOT NULL DEFAULT 0,
                current_action_id INTEGER NULL,
                departure_engaged INTEGER NOT NULL DEFAULT 0,
                laser_next_target_at $nullableText,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                destroyed_at $nullableText,
                FOREIGN KEY(fleet_id) REFERENCES others_fleets(id) ON DELETE CASCADE
            )",
            "CREATE INDEX IF NOT EXISTS idx_others_ships_fleet_status ON others_ships(fleet_id, status, public_id)",
            "CREATE INDEX IF NOT EXISTS idx_others_ships_sector_status ON others_ships(sector_x, sector_y, sector_z, status)",
            "CREATE INDEX IF NOT EXISTS idx_others_ships_current_action ON others_ships(current_action_id)",
            "CREATE TABLE IF NOT EXISTS others_auxiliaries (
                id $id,
                public_id $caseSensitiveText NOT NULL UNIQUE,
                ship_id INTEGER NOT NULL,
                status $text NOT NULL DEFAULT 'inactive',
                location_type $text NOT NULL DEFAULT 'embarked',
                spatial_state $text NOT NULL DEFAULT 'drifting',
                sector_x INTEGER NULL,
                sector_y INTEGER NULL,
                sector_z INTEGER NULL,
                object_id $nullableText,
                current_action_id INTEGER NULL,
                cargo_deuterium $decimal NOT NULL DEFAULT 0,
                cargo_metals $decimal NOT NULL DEFAULT 0,
                cargo_ice $decimal NOT NULL DEFAULT 0,
                cargo_carbon_compounds $decimal NOT NULL DEFAULT 0,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                destroyed_at $nullableText,
                FOREIGN KEY(ship_id) REFERENCES others_ships(id) ON DELETE CASCADE
            )",
            "CREATE INDEX IF NOT EXISTS idx_others_aux_ship_status ON others_auxiliaries(ship_id, status, public_id)",
            "CREATE INDEX IF NOT EXISTS idx_others_aux_sector_location ON others_auxiliaries(sector_x, sector_y, sector_z, location_type, public_id)",
            "CREATE INDEX IF NOT EXISTS idx_others_aux_current_action ON others_auxiliaries(current_action_id)",
            "CREATE TABLE IF NOT EXISTS others_inventory_resources (
                id $id,
                ship_id INTEGER NOT NULL,
                resource_type $text NOT NULL,
                amount $decimal NOT NULL DEFAULT 0,
                reserved_amount $decimal NOT NULL DEFAULT 0,
                updated_at $text NOT NULL,
                UNIQUE(ship_id, resource_type),
                FOREIGN KEY(ship_id) REFERENCES others_ships(id) ON DELETE CASCADE
            )",
            "CREATE INDEX IF NOT EXISTS idx_others_inventory_resources_ship ON others_inventory_resources(ship_id)",
            "CREATE TABLE IF NOT EXISTS others_inventory_items (
                id $id,
                public_id $caseSensitiveText NOT NULL UNIQUE,
                ship_id INTEGER NOT NULL,
                type $text NOT NULL,
                container_space $decimal NOT NULL,
                reserved_action_id INTEGER NULL,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                FOREIGN KEY(ship_id) REFERENCES others_ships(id) ON DELETE CASCADE
            )",
            "CREATE INDEX IF NOT EXISTS idx_others_inventory_items_ship_reserved ON others_inventory_items(ship_id, reserved_action_id, public_id)",
            "CREATE TABLE IF NOT EXISTS others_actions (
                id $id,
                public_id $caseSensitiveText NOT NULL UNIQUE,
                fleet_id INTEGER NOT NULL,
                ship_id INTEGER NULL,
                auxiliary_id INTEGER NULL,
                type $text NOT NULL,
                status $text NOT NULL,
                actor_kind $text NOT NULL,
                actor_public_id $caseSensitiveText NOT NULL,
                payload_json TEXT NOT NULL,
                result_json TEXT NULL,
                error_json TEXT NULL,
                ends_at $nullableText,
                cancelable_until $nullableText,
                completed_at $nullableText,
                scheduled_event_id INTEGER NULL,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                FOREIGN KEY(fleet_id) REFERENCES others_fleets(id),
                FOREIGN KEY(ship_id) REFERENCES others_ships(id),
                FOREIGN KEY(auxiliary_id) REFERENCES others_auxiliaries(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_others_actions_fleet_status ON others_actions(fleet_id, status, created_at)",
            "CREATE INDEX IF NOT EXISTS idx_others_actions_ship_status ON others_actions(ship_id, status, created_at)",
            "CREATE INDEX IF NOT EXISTS idx_others_actions_due ON others_actions(status, ends_at)",
            "CREATE TABLE IF NOT EXISTS others_movements (
                id $id,
                action_id INTEGER NOT NULL UNIQUE,
                ship_id INTEGER NOT NULL,
                source_x INTEGER NOT NULL,
                source_y INTEGER NOT NULL,
                source_z INTEGER NOT NULL,
                target_x INTEGER NOT NULL,
                target_y INTEGER NOT NULL,
                target_z INTEGER NOT NULL,
                fuel_cost $decimal NOT NULL,
                leave_auxiliaries_behind INTEGER NOT NULL DEFAULT 0,
                phase $text NOT NULL,
                depart_at $text NOT NULL,
                arrive_at $text NOT NULL,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                FOREIGN KEY(action_id) REFERENCES others_actions(id),
                FOREIGN KEY(ship_id) REFERENCES others_ships(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_others_movements_ship_phase ON others_movements(ship_id, phase)",
            "CREATE TABLE IF NOT EXISTS others_inventory_transfers (
                id $id,
                public_id $caseSensitiveText NOT NULL UNIQUE,
                action_id INTEGER NOT NULL UNIQUE,
                source_ship_id INTEGER NOT NULL,
                target_ship_id INTEGER NOT NULL,
                auxiliary_id INTEGER NOT NULL,
                kind $text NOT NULL,
                resource_type $nullableText,
                amount $decimal NULL,
                item_ids_json TEXT NOT NULL,
                status $text NOT NULL,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                FOREIGN KEY(action_id) REFERENCES others_actions(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_others_transfers_source_status ON others_inventory_transfers(source_ship_id, status)",
            "CREATE TABLE IF NOT EXISTS others_crafts (
                id $id,
                public_id $caseSensitiveText NOT NULL UNIQUE,
                action_id INTEGER NOT NULL UNIQUE,
                ship_id INTEGER NOT NULL,
                assistant_auxiliary_id INTEGER NOT NULL,
                recipe_id $text NOT NULL,
                ingredients_json TEXT NOT NULL,
                output_space $decimal NOT NULL DEFAULT 0,
                status $text NOT NULL,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                FOREIGN KEY(action_id) REFERENCES others_actions(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_others_crafts_ship_status ON others_crafts(ship_id, status, public_id)",
            "CREATE TABLE IF NOT EXISTS others_harvests (
                id $id,
                action_id INTEGER NOT NULL UNIQUE,
                ship_id INTEGER NOT NULL,
                target_object_id $caseSensitiveText NOT NULL,
                phase $text NOT NULL,
                phase_started_at $text NOT NULL,
                auxiliary_count INTEGER NOT NULL,
                reserved_capacity $decimal NOT NULL,
                biological_carbon $decimal NOT NULL DEFAULT 0,
                pending_output_json TEXT NULL,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                FOREIGN KEY(action_id) REFERENCES others_actions(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_others_harvests_ship_phase ON others_harvests(ship_id, phase)",
            "CREATE TABLE IF NOT EXISTS others_swarm_participants (
                id $id,
                action_id INTEGER NOT NULL,
                auxiliary_id INTEGER NOT NULL,
                created_at $text NOT NULL,
                UNIQUE(action_id, auxiliary_id),
                FOREIGN KEY(action_id) REFERENCES others_actions(id),
                FOREIGN KEY(auxiliary_id) REFERENCES others_auxiliaries(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_others_swarm_participants_auxiliary ON others_swarm_participants(auxiliary_id)",
            "CREATE TABLE IF NOT EXISTS others_projectiles (
                id $id,
                public_id $caseSensitiveText NOT NULL UNIQUE,
                launch_id INTEGER NOT NULL UNIQUE,
                action_id INTEGER NULL UNIQUE,
                launcher_kind $text NOT NULL,
                launcher_public_id $caseSensitiveText NOT NULL,
                target_public_id $caseSensitiveText NOT NULL,
                target_kind $text NOT NULL,
                sector_x INTEGER NOT NULL,
                sector_y INTEGER NOT NULL,
                sector_z INTEGER NOT NULL,
                status $text NOT NULL,
                launched_at $text NOT NULL,
                impact_at $text NOT NULL,
                created_at $text NOT NULL,
                updated_at $text NOT NULL
            )",
            "CREATE INDEX IF NOT EXISTS idx_others_projectiles_sector_status ON others_projectiles(sector_x, sector_y, sector_z, status)",
            "CREATE INDEX IF NOT EXISTS idx_others_projectiles_due ON others_projectiles(status, impact_at)",
            "CREATE TABLE IF NOT EXISTS missile_launches (
                id $id,
                public_id $caseSensitiveText NOT NULL UNIQUE,
                launcher_kind $text NOT NULL,
                launcher_public_id $caseSensitiveText NOT NULL,
                player_id INTEGER NOT NULL,
                probe_id INTEGER NULL,
                manny_id INTEGER NULL,
                probe_item_id INTEGER NULL,
                others_action_id INTEGER NULL,
                others_item_id INTEGER NULL,
                target_public_id $caseSensitiveText NOT NULL,
                target_kind $text NOT NULL,
                sector_x INTEGER NOT NULL,
                sector_y INTEGER NOT NULL,
                sector_z INTEGER NOT NULL,
                status $text NOT NULL,
                projectile_public_id $caseSensitiveText NULL,
                launch_at $text NOT NULL,
                impact_at $nullableText,
                result $nullableText,
                scheduled_event_id INTEGER NULL,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                FOREIGN KEY(player_id) REFERENCES players(id),
                FOREIGN KEY(probe_id) REFERENCES neumann_probes(id),
                FOREIGN KEY(manny_id) REFERENCES mannies(id),
                FOREIGN KEY(probe_item_id) REFERENCES probe_items(id),
                FOREIGN KEY(others_action_id) REFERENCES others_actions(id),
                FOREIGN KEY(others_item_id) REFERENCES others_inventory_items(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_missile_launches_probe_item_active ON missile_launches(probe_item_id, status)",
            "CREATE INDEX IF NOT EXISTS idx_missile_launches_others_item_active ON missile_launches(others_item_id, status)",
            "CREATE INDEX IF NOT EXISTS idx_missile_launches_player ON missile_launches(player_id, public_id)",
            "CREATE INDEX IF NOT EXISTS idx_missile_launches_status_due ON missile_launches(status, launch_at)",
            "CREATE TABLE IF NOT EXISTS others_laser_locks (
                id $id,
                action_id INTEGER NOT NULL UNIQUE,
                ship_id INTEGER NOT NULL,
                target_kind $text NOT NULL,
                target_public_id $caseSensitiveText NOT NULL,
                sector_x INTEGER NOT NULL,
                sector_y INTEGER NOT NULL,
                sector_z INTEGER NOT NULL,
                status $text NOT NULL,
                started_at $nullableText,
                accounted_until $nullableText,
                next_damage_at $nullableText,
                exhausts_at $nullableText,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                FOREIGN KEY(action_id) REFERENCES others_actions(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_others_laser_ship_status ON others_laser_locks(ship_id, status)",
            "CREATE TABLE IF NOT EXISTS others_projectile_history (
                id $id,
                projectile_public_id $caseSensitiveText NOT NULL UNIQUE,
                action_public_id $caseSensitiveText NOT NULL,
                result $text NOT NULL,
                details_json TEXT NOT NULL,
                resolved_at $text NOT NULL
            )",
            "CREATE TABLE IF NOT EXISTS others_damage_events (
                id $id,
                event_key $caseSensitiveText NOT NULL UNIQUE,
                target_kind $text NOT NULL,
                target_public_id $caseSensitiveText NOT NULL,
                damage INTEGER NOT NULL,
                created_at $text NOT NULL
            )",
            "CREATE INDEX IF NOT EXISTS idx_others_damage_target ON others_damage_events(target_kind, target_public_id)",
            "CREATE TABLE IF NOT EXISTS others_cross_store_operations (
                id $id,
                public_id $caseSensitiveText NOT NULL UNIQUE,
                action_id INTEGER NULL,
                operation_type $text NOT NULL,
                payload_json TEXT NOT NULL,
                sql_applied INTEGER NOT NULL DEFAULT 0,
                sector_applied INTEGER NOT NULL DEFAULT 0,
                status $text NOT NULL,
                created_at $text NOT NULL,
                updated_at $text NOT NULL
            )",
            "CREATE INDEX IF NOT EXISTS idx_others_cross_store_status ON others_cross_store_operations(status, created_at)",
            "CREATE TABLE IF NOT EXISTS forum_categories (
                id $id,
                name $text NOT NULL,
                description TEXT NULL,
                sort_order INTEGER NOT NULL DEFAULT 0,
                created_at $text NOT NULL,
                updated_at $text NOT NULL
            )",
            "CREATE INDEX IF NOT EXISTS idx_forum_categories_sort_order ON forum_categories(sort_order, id)",
            "CREATE TABLE IF NOT EXISTS forum_posts (
                id $id,
                category_id INTEGER NOT NULL,
                author_player_id INTEGER NOT NULL,
                title $text NOT NULL,
                pinned $boolean,
                first_message_id INTEGER NULL,
                message_count INTEGER NOT NULL DEFAULT 0,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                last_message_at $text NOT NULL,
                FOREIGN KEY(category_id) REFERENCES forum_categories(id),
                FOREIGN KEY(author_player_id) REFERENCES players(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_forum_posts_recent ON forum_posts(pinned, last_message_at, id)",
            "CREATE INDEX IF NOT EXISTS idx_forum_posts_category_recent ON forum_posts(category_id, pinned, last_message_at, id)",
            "CREATE TABLE IF NOT EXISTS forum_messages (
                id $id,
                post_id INTEGER NOT NULL,
                author_player_id INTEGER NOT NULL,
                body TEXT NOT NULL,
                created_at $text NOT NULL,
                updated_at $text NOT NULL,
                edited_at $nullableText,
                FOREIGN KEY(post_id) REFERENCES forum_posts(id),
                FOREIGN KEY(author_player_id) REFERENCES players(id)
            )",
            "CREATE INDEX IF NOT EXISTS idx_forum_messages_post_recent ON forum_messages(post_id, created_at, id)",
        ];

        $statements = array_values(array_filter($statements, static fn(string $statement): bool => $statement !== ''));

        if ($this->driver !== 'mysql') {
            return $statements;
        }

        return array_map(fn(string $statement): string => $this->withMysqlEngine($statement), $statements);
    }

    private function withMysqlEngine(string $statement): string
    {
        if (!str_starts_with(strtoupper(ltrim($statement)), 'CREATE TABLE')) {
            return $statement;
        }

        if (stripos($statement, 'ENGINE=') !== false) {
            return $statement;
        }

        return rtrim($statement) . ' ENGINE=InnoDB';
    }
}
